databases:
  - name: electricars
    databaseName: electricars
    user: davidcibin

services:
  - type: web
    name: electricars
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "gunicorn electricars.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: electricars
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4