# Generated by Django 3.2.2 on 2021-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='insurance',
            field=models.CharField(choices=[('N', 'No Coverage'), ('F', 'Full Coverage')], default='N', max_length=1),
        ),
    ]
