# Generated by Django 3.2.2 on 2021-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_booking_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address1',
            field=models.CharField(default=1, help_text='Address 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Address2',
            field=models.CharField(default=1, help_text='Address 2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=1, help_text='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=1, help_text='state', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(default=1, help_text='zipcode', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(help_text='bbbbio', max_length=100),
        ),
    ]
