# Generated by Django 3.2.2 on 2021-05-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
        ),
    ]
