# Generated by Django 3.2.2 on 2021-05-12 15:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='suitcase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(help_text='Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(help_text='State', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(help_text='Zip', max_length=5),
        ),
    ]
