# Generated by Django 3.2.2 on 2021-05-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210513_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='creator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
