# Generated by Django 3.2.2 on 2021-05-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210512_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='creator',
        ),
    ]
