# Generated by Django 3.2.2 on 2021-05-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
